# Generated by Django 5.1.1 on 2024-10-15 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barberos',
            fields=[
                ('id_barbero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCitas',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tiempo_aproximado', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_finalizacion', models.DateTimeField()),
                ('token', models.BooleanField(default=True)),
                ('id_barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.barberos')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.cliente')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.estadocitas')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.servicios')),
            ],
        ),
    ]
