# Generated by Django 5.1.1 on 2024-10-27 19:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_barberos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='tokenName',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
